/**
 * Autogenerated
 *
 */

package coherence;
public class Person {

  public String firstname;
  public String lastname;
  public String phone;
  public int age;

  /**
   * Gets the value of the 'firstname' field.
   */
  public String getFirstname() {
    return firstname;
  }

  /**
   * Sets the value of the 'firstname' field.
   * @param value the value to set.
   */
  public void setFirstname(String value) {
    this.firstname = value;
  }

  /**
   * Gets the value of the 'lastname' field.
   */
  public String getLastname() {
    return lastname;
  }

  /**
   * Sets the value of the 'lastname' field.
   * @param value the value to set.
   */
  public void setLastname(String value) {
    this.lastname = value;
  }

  /**
   * Gets the value of the 'phone' field.
   */
  public String getPhone() {
    return phone;
  }

  /**
   * Sets the value of the 'phone' field.
   * @param value the value to set.
   */
  public void setPhone(String value) {
    this.phone = value;
  }

  /**
   * Gets the value of the 'age' field.
   */
  public Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(Integer value) {
    this.age = value;
  }
}
