/*-
 * Copyright (C) 2011, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This file was distributed by Oracle as part of a version of Oracle NoSQL
 * Database made available at:
 *
 * http://www.oracle.com/technetwork/database/database-technologies/nosqldb/downloads/index.html
 *
 * Please see the LICENSE file included in the top-level directory of the
 * appropriate version of Oracle NoSQL Database for a copy of the license and
 * additional information.
 */

package oracle.kv.impl.mgmt;

import oracle.kv.impl.admin.param.AdminParams;
import oracle.kv.impl.admin.param.ArbNodeParams;
import oracle.kv.impl.admin.param.RepNodeParams;
import oracle.kv.impl.measurement.ProxiedServiceStatusChange;
import oracle.kv.impl.sna.ServiceManager;
import oracle.kv.impl.topo.ArbNodeId;
import oracle.kv.impl.topo.RepNodeId;
import oracle.kv.impl.util.ServiceStatusTracker;

/**
 * This is the external interface to standardized monitoring and management,
 * used by the StorageNodeAgent
 */
public interface MgmtAgent {

    /**
     * For the SNA's status, we just add a listener to its status tracker.
     */
    void setSnaStatusTracker(ServiceStatusTracker snaStatusTracker);

    /**
     * Notify the agent of a new RepNode to track.
     */
    void addRepNode(RepNodeParams rnp, ServiceManager mgr)
        throws Exception;

    /**
     * Stop tracking the indicated RepNode.
     */
    void removeRepNode(RepNodeId rnid);

    /**
     * Notify the agent of a new ArbNode to track.
     */
    void addArbNode(ArbNodeParams arp, ServiceManager mgr)
        throws Exception;

    /**
     * Stop tracking the indicated ArbNode.
     */
    void removeArbNode(ArbNodeId arbid);


    /**
     * Notify the agent of a local Admin instance.
     */
    void addAdmin(AdminParams ap, ServiceManager mgr)
        throws Exception;

    /**
     * Stop tracking the Admin.
     */
    void removeAdmin();

    /**
     * Shut down the agent.  This should eliminate all threads under the agent's
     * control, so that the SNA process may shut down cleanly.
     */
    void shutdown();

    /**
     * Handle a "proxied" status change generated by the process manager.  This
     * happens when, for example, a RepNode crashes and can't report its own
     * status; then the SNA's process manager reports a status of
     * ERROR_NO_RESTART.
     */
    void proxiedStatusChange(ProxiedServiceStatusChange sc);

    /**
     * Check whether the  MgmtAgent is configured with the given parameters.
     */
    boolean checkParametersEqual(int pollp, String traph, int trapp);
}
